In [10]:
import pandas as pd
import numpy as np

# **Import Data**

In [11]:
!gdown --id 1W7v3NevY_SgZoCnh78rEwUVyvk3X91Qv

/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1W7v3NevY_SgZoCnh78rEwUVyvk3X91Qv
To: /content/Test1to5.csv
100% 9.19M/9.19M [00:00<00:00, 44.9MB/s]


In [12]:
#read csv file
dataset = pd.read_csv('/content/Test1to5.csv')

In [13]:
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

برای تبدیل فیچر کتگوری به فیچر **عددی** یکی از دو روش زیر را انتخاب می کنیم

In [14]:
# Step 2 - Convert Label to number
#from sklearn.preprocessing import LabelEncoder
#labelEncoder_Label =  LabelEncoder() #from sklearn
#y = labelEncoder_Label.fit_transform(y)

In [15]:
# Step 2 - Convert Label to number
#change the target to categorical
target = dataset['Label'].astype('category')
y = target.cat.codes

In [16]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [17]:
#X=X.astype('float')

In [18]:
print(f"Shape Data:",X.shape)
print(f"Shape Label:",y.shape)

Shape Data: (8000, 102)
Shape Label: (8000,)


In [19]:
# Step 4 - Split Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [20]:
from sklearn.svm import SVC
SVC_lin = SVC(kernel='linear', C=250,random_state=42)
SVC_lin.fit(X_train, y_train)

SVC(C=250, kernel='linear', random_state=42)

kernel{‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’} or callable, default=’rbf’

    Specifies the kernel type to be used in the algorithm. If none is given, ‘rbf’ will be used. If a callable is given it is used to pre-compute the kernel matrix from data matrices; that matrix should be an array of shape (n_samples, n_samples).


In [21]:

y_pred = SVC_lin.predict(X_test)

print("y_pred[: 20]:",y_pred[: 20])
print("y_Exact[: 20]:",y_test[: 20])

y_pred[: 20]: ['M3' 'M5' 'M1' 'M5' 'M3' 'M5' 'M2' 'M5' 'M5' 'M1' 'M2' 'M3' 'M1' 'M2'
 'M1' 'M3' 'M2' 'M2' 'M2' 'M2']
y_Exact[: 20]: ['M3' 'M5' 'M1' 'M5' 'M3' 'M5' 'M2' 'M5' 'M5' 'M1' 'M2' 'M2' 'M1' 'M2'
 'M1' 'M3' 'M2' 'M2' 'M2' 'M3']


In [22]:

SVC_lin.score(X_test, y_test)

0.774375

In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          M1       0.70      0.73      0.71       392
          M2       0.73      0.71      0.72       398
          M3       0.81      0.78      0.79       411
          M5       0.86      0.87      0.86       399

    accuracy                           0.77      1600
   macro avg       0.77      0.77      0.77      1600
weighted avg       0.77      0.77      0.77      1600



In [25]:
# Step 7 - Confusion Matrix
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)
accuracy = metrics.accuracy_score(y_test, y_pred)
print("Accuracy score:",accuracy)
#precision = metrics.precision_score(y_test, y_pred)
#print("Precision score:",precision)
#recall = metrics.recall_score(y_test, y_pred)
#print("Recall score:",recall)

[[285  50  24  33]
 [ 57 284  45  12]
 [ 28  47 322  14]
 [ 36   6   9 348]]
Accuracy score: 0.774375


In [26]:

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report


from sklearn.model_selection import cross_val_score

In [55]:
#applying built-in function / p is related Minkowski metric
knn = KNeighborsClassifier(n_neighbors=4, algorithm='kd_tree', p=2)

In [56]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='kd_tree', n_neighbors=4)

algorithm : {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'
    Algorithm used to compute the nearest neighbors:

In [57]:
y_pred2 = knn.predict(X_test)

In [58]:
knn.score(X_test, y_test)

0.629375

In [59]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

          M1       0.50      0.72      0.59       392
          M2       0.65      0.47      0.54       398
          M3       0.77      0.67      0.72       411
          M5       0.68      0.65      0.67       399

    accuracy                           0.63      1600
   macro avg       0.65      0.63      0.63      1600
weighted avg       0.65      0.63      0.63      1600



#Logistic Regression

In [32]:
# Step 5 - Logistic Regression Classifier
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0, solver="liblinear")
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [33]:
y_pred = classifier.predict(X_test)

In [44]:
classifier.score(X_test, y_test)

0.644375

In [35]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

          M1       0.50      0.72      0.59       392
          M2       0.65      0.47      0.54       398
          M3       0.77      0.67      0.72       411
          M5       0.68      0.65      0.67       399

    accuracy                           0.63      1600
   macro avg       0.65      0.63      0.63      1600
weighted avg       0.65      0.63      0.63      1600



In [54]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0, solver="saga",penalty='l2')
classifier.fit(X_train, y_train)
#
y_pred = classifier.predict(X_test)
classifier.score(X_test, y_test)
print(classification_report(y_test, y_pred2))


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


              precision    recall  f1-score   support

          M1       0.50      0.72      0.59       392
          M2       0.65      0.47      0.54       398
          M3       0.77      0.67      0.72       411
          M5       0.68      0.65      0.67       399

    accuracy                           0.63      1600
   macro avg       0.65      0.63      0.63      1600
weighted avg       0.65      0.63      0.63      1600



تست مربوط به کارکرد عملی

In [37]:
!gdown --id 1Sc6K9szbSxVSjRGM32OMrmKAhXh3fReS
#read csv file
Dorfaki_test = pd.read_csv('/content/TT4.csv')

/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1Sc6K9szbSxVSjRGM32OMrmKAhXh3fReS
To: /content/TT4.csv
100% 463k/463k [00:00<00:00, 7.90MB/s]


In [38]:
X_Dorfaki_test = Dorfaki_test.iloc[:,:-1].values
y_Dorfaki_test = Dorfaki_test.iloc[:,-1].values

In [ ]:
# Step 2 - Convert Label to number
#change the target to categorical
#target = Dorfaki_test['Label'].astype('category')
#y_Dorfaki_test = target.cat.codes

In [ ]:
# Step 2 - Convert Label to number
#from sklearn.preprocessing import LabelEncoder
#labelEncoder_Label =  LabelEncoder() #from sklearn
#y_Dorfaki_test = labelEncoder_Label.fit_transform(y_Dorfaki_test)

In [ ]:
y_pred = SVC_lin.predict(X_Dorfaki_test)

print("y_pred:",y_pred)
print("y_Exact:",y_Dorfaki_test)

In [42]:
SVC_lin.score(X_Dorfaki_test, y_Dorfaki_test)

0.004975124378109453

# ANN

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential#مدل مورد نظر اعم از متوالی و تابعی را فراخوانی می کنیم
from tensorflow.keras.layers import Dense, Activation,Input# لایه های کام اف سی و همچنین تابع فعال ساز مانند سیگموند را هم به عنوان یک لایه فراخوانی می کنیم
from tensorflow.keras.optimizers import Adam, Adagrad # روند ترین کردن یعنی استفاده از گرادیان کاهشی یا روش های مشتبرگرفته از آن در این قسمت فرا خوانی می شود

In [ ]:
n_classes = len(set(y_train))#تعداد کلاس ها با توجه به تنوع لیبل ها
n_samples, n_features = X_train.shape#تعداد سطر و تعداد ستون های ماتریس ترین

In [ ]:
from sklearn.svm import SVC
from time import perf_counter
import numpy as np
import tensorflow as tf
#Import the libraries for neural networks
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

In [ ]:
# Building the neural network (Functional API)
##define input layer
input_layer = Input(shape=(n_features,), name='input_layer')

##Defining 2 hidden layers
Layer_1 = Dense(20, activation="relu", name='Layer_1')(input_layer)
Layer_2 = Dense(40, activation="relu", name='Layer_2')(Layer_1)

##Defining  output layer y1
output = Dense(n_classes, activation="softmax", name='output')(Layer_2)

##Defining the model by specifying the input and output layers
fc_model = Model(inputs=input_layer, outputs=output)

NameError: ignored

In [ ]:
fc_model.summary()

NameError: ignored

In [ ]:
#model compile
metric = tf.keras.metrics.CategoricalAccuracy()
opt = tf.keras.optimizers.Adam(learning_rate=0.0001)
loss = tf.keras.losses.CategoricalCrossentropy()
fc_model.compile(loss=loss,
                 optimizer=opt,
                 metrics=metric)

In [ ]:
#model fit and prdict
history = fc_model.fit(X_train, y_train, epochs=2, verbose=True,
          batch_size=128, validation_data=(X_test, y_test))

Epoch 1/2


ValueError: ignored

In [ ]:


#input_layer = Input(shape=(n_features,), name='input_layer')

model_1=Sequential()
model_1.add(Dense(8,activation='relu'))#اینجا یک لایه با 8نود که تابع فعال ساز رلو روی آن است ساخته ایم
model_1.add(Dense(4,activation='relu'))
model_1.add(Dense(10,activation='softmax'))

#روند انجام ترین و نوع خطا در ارزیابی روی مدل را تعیین می کنیم
#metric = tf.keras.metrics.metrics=['accuracy']()
opt = tf.keras.optimizers.Adam(learning_rate=0.0001)
loss = tf.keras.losses.SparseCategoricalCrossentropy()

model_1.compile(loss=loss,optimizer=opt)


model_1.fit(x=X_train,y=y_train,
          validation_data=(X_test,y_test),
          batch_size=32, epochs=30)

In [ ]:
##Import the libraries
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.optimizers import Adam

In [ ]:
##Import the libraries
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
## Creating the layers
input_layer = Input(shape=(3,))
Layer_1 = Dense(4, activation="relu")(input_layer)
Layer_2 = Dense(4, activation="relu")(Layer_1)
output_layer = Dense(1, activation="linear")(Layer_2)
##Defining the model by specifying the input and output layers
model = Model(inputs=input_layer, outputs=output_layer)
## defining the optimiser and loss function
model.compile(optimizer='adam', loss='mse')
## training the model
model.fit(X_train, y_train, epochs=40,batch_size=128, validation_data=(X_test,y_test))

In [ ]:
model_1.summary()